[project]
name = "bigraph-schema"
version = "0.0.61"
description = "A serializable type schema for compositional systems biology"
readme = "README.md"
requires-python = "==3.12.9"
dependencies = [
    "numpy",
    "parsimonious",
    "fire",
    "pytest",
    "pint",
    "plum-dispatch"
]

[tool.setuptools]
packages = [
    "bigraph_schema"
]


